name: Deploy PavelBotov

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy locally
        run: |
          cd /opt/pavelbotov
          git fetch origin main
          git reset --hard origin/main
          docker compose down
          docker compose up -d --build